# TCL File Generated by Component Editor 22.1
# Thu Jan 30 22:35:36 CET 2025
# DO NOT MODIFY


# 
# VGA_IP "VGA_IP" v1.0
# Menyar_Hees 2025.01.30.22:35:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VGA_IP
# 
set_module_property DESCRIPTION ""
set_module_property NAME VGA_IP
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP own_ip
set_module_property AUTHOR Menyar_Hees
set_module_property DISPLAY_NAME VGA_IP
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL case_3_vga_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DP_RAM.vhd VHDL PATH HDL/DP_RAM.vhd
add_fileset_file VGA_Sync.vhd VHDL PATH HDL/VGA_Sync.vhd
add_fileset_file case_3_vga_ip.vhd VHDL PATH HDL/case_3_vga_ip.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink_25
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock_sink_25
# 
add_interface clock_sink_25 clock end
set_interface_property clock_sink_25 clockRate 0
set_interface_property clock_sink_25 ENABLED true
set_interface_property clock_sink_25 EXPORT_OF ""
set_interface_property clock_sink_25 PORT_NAME_MAP ""
set_interface_property clock_sink_25 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_25 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_25 clk_25 clk Input 1


# 
# connection point clock_sink_50
# 
add_interface clock_sink_50 clock end
set_interface_property clock_sink_50 clockRate 0
set_interface_property clock_sink_50 ENABLED true
set_interface_property clock_sink_50 EXPORT_OF ""
set_interface_property clock_sink_50 PORT_NAME_MAP ""
set_interface_property clock_sink_50 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_50 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_50 clk_50 clk Input 1


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock_sink_25
set_interface_property avalon_slave_0_1 associatedReset reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 avalon_cs_n chipselect_n Input 1
add_interface_port avalon_slave_0_1 avalon_addr address Input 17
add_interface_port avalon_slave_0_1 avalon_din writedata Input 32
add_interface_port avalon_slave_0_1 avalon_dout readdata Output 32
add_interface_port avalon_slave_0_1 avalon_read_n read_n Input 1
add_interface_port avalon_slave_0_1 avalon_write_n write_n Input 1
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock_sink_25
set_interface_property conduit_end_1 associatedReset reset
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 VGA_B vga_b Output 4
add_interface_port conduit_end_1 VGA_G vga_g Output 4
add_interface_port conduit_end_1 VGA_HS vga_hs Output 1
add_interface_port conduit_end_1 VGA_R vga_r Output 4
add_interface_port conduit_end_1 VGA_VS vga_vs Output 1

